version: 2.1

jobs:
    build:
        docker:
            - image: python:3.7.3-stretch

        working_directory: ~/repo

        steps:
            - checkout
    
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    - v1-dependencies-
            
            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    make install
                    # Install hadolint
                    wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                    chmod +x /bin/hadolint
            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}
            
            # run lint!
            - run:
                name: run lint
                command: |
                    . venv/bin/activate
                    make lint
  
                    
    docker-push:
        machine: true
        steps:
            - checkout

            - run:
                name: build and push docker image
                command: |
                    docker build --tag=udacity-capstone . && \
                    docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" && \
                    docker tag udacity-capstone minaeshak/udacity-capstone && \
                    docker push minaeshak/udacity-capstone
                    
    deploy-eks:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                name: install kubectl & eksctl
                command: | 
                    yum install gzip -y 
                    yum install tar -y     
                    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
                    mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
                    echo 'export PATH=$PATH:$HOME/bin' >> ~/.bash_profile
                    kubectl version --short --client
                    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
                    mv /tmp/eksctl /usr/local/bin
                    eksctl version
                
            - run:
                name: create EKS cluster
                command: | 
                    eksctl create cluster \
                    --name udacity-capstone \
                    --region eu-central-1 \
                    --with-oidc \
                    --ssh-access \
                    --ssh-public-key udacity-frankfurt-v2
            - run:
                name: deploy the app
                command: |
                     kubectl apply -f deployment.yml 

    
                
workflows:
  default:
    jobs:
#      - build
#        - docker-push
        - deploy-eks
#          requires: [docker-push]